container:
  image: cirrusci/flutter:latest

format_task:
  script: find lib -name "*.dart" -exec flutter format -n --set-exit-if-changed {} \;

build_task:
  script: flutter build aot

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test
